[0m14:00:44.348264 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023A5C78E630>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023A5C54FCE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023A5C81B6E0>]}


============================== 14:00:44.356892 | 1c7d6ebd-6f2c-4fd1-8f31-b0a6228a3ea4 ==============================
[0m14:00:44.356892 [info ] [MainThread]: Running with dbt=1.8.3
[0m14:00:44.361410 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Felip\\.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt init adventureworks', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:00:44.405170 [debug] [MainThread]: Starter project path: c:\venv\dbt\Lib\site-packages\dbt\include\starter_project
[0m14:00:44.438198 [info ] [MainThread]: 
Your new dbt project "adventureworks" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:00:44.438198 [info ] [MainThread]: Setting up your profile.
[0m14:03:50.700596 [info ] [MainThread]: Profile adventureworks written to C:\Users\Felip\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m14:03:50.700596 [debug] [MainThread]: Command `dbt init` succeeded at 14:03:50.700596 after 186.60 seconds
[0m14:03:50.700596 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023A5D54EBA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023A5C99B890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000023A5CA38560>]}
[0m14:03:50.700596 [debug] [MainThread]: Flushing usage events
[0m14:04:28.328388 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002FC70147B60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002FC70147BF0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002FC701479E0>]}


============================== 14:04:28.335998 | 80bb489d-20fa-489c-8101-615a2b3e093e ==============================
[0m14:04:28.335998 [info ] [MainThread]: Running with dbt=1.8.3
[0m14:04:28.335998 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Felip\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:04:28.360636 [info ] [MainThread]: dbt version: 1.8.3
[0m14:04:28.360636 [info ] [MainThread]: python version: 3.12.4
[0m14:04:28.360636 [info ] [MainThread]: python path: c:\venv\dbt\Scripts\python.exe
[0m14:04:28.366649 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:04:28.766774 [info ] [MainThread]: Using profiles dir at C:\Users\Felip\.dbt
[0m14:04:28.766774 [info ] [MainThread]: Using profiles.yml file at C:\Users\Felip\.dbt\profiles.yml
[0m14:04:28.774796 [info ] [MainThread]: Using dbt_project.yml file at c:\felipeyoshi\modern-data-stack\dbt\dbt_project.yml
[0m14:04:28.774796 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:04:28.774796 [debug] [MainThread]: Command `dbt debug` failed at 14:04:28.774796 after 0.84 seconds
[0m14:04:28.780032 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002FC6D167B60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002FC70147C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002FC70E6B2F0>]}
[0m14:04:28.781099 [debug] [MainThread]: Flushing usage events
[0m14:05:35.718585 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276A5549C70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276A5549DC0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276A4FCDA90>]}


============================== 14:05:35.726912 | d1887223-e43f-45fc-a886-99e7fce6daaa ==============================
[0m14:05:35.726912 [info ] [MainThread]: Running with dbt=1.8.3
[0m14:05:35.726912 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\Felip\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m14:05:35.750681 [info ] [MainThread]: dbt version: 1.8.3
[0m14:05:35.751213 [info ] [MainThread]: python version: 3.12.4
[0m14:05:35.752545 [info ] [MainThread]: python path: c:\venv\dbt\Scripts\python.exe
[0m14:05:35.753595 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m14:05:36.237963 [info ] [MainThread]: Using profiles dir at C:\Users\Felip\.dbt
[0m14:05:36.237963 [info ] [MainThread]: Using profiles.yml file at C:\Users\Felip\.dbt\profiles.yml
[0m14:05:36.237963 [info ] [MainThread]: Using dbt_project.yml file at c:\felipeyoshi\modern-data-stack\dbt\dbt_project.yml
[0m14:05:36.237963 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m14:05:36.245904 [debug] [MainThread]: Command `dbt debug` failed at 14:05:36.245904 after 0.76 seconds
[0m14:05:36.245904 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276A53EB0B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002769F653B30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276A5549DC0>]}
[0m14:05:36.245904 [debug] [MainThread]: Flushing usage events
[0m18:28:38.593281 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A9AF53170>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A97783410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A986AAAE0>]}


============================== 18:28:38.610318 | 425506da-8cdc-4c26-9ed3-de3c3aea3f49 ==============================
[0m18:28:38.610318 [info ] [MainThread]: Running with dbt=1.8.3
[0m18:28:38.610318 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Felip\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:28:38.610318 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path c:\felipeyoshi\modern-data-stack\dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:28:38.610318 [debug] [MainThread]: Command `dbt run` failed at 18:28:38.610318 after 0.23 seconds
[0m18:28:38.610318 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A9AE32C60>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A9ACE0800>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019A94E4C710>]}
[0m18:28:38.610318 [debug] [MainThread]: Flushing usage events
[0m18:30:29.405064 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000169E9EDC5C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000169E9EDC530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000169E9EDD310>]}


============================== 18:30:29.405064 | 1c35afb0-da65-4081-badb-51d0d0b222f4 ==============================
[0m18:30:29.405064 [info ] [MainThread]: Running with dbt=1.8.3
[0m18:30:29.405064 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Felip\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m18:30:29.438064 [info ] [MainThread]: dbt version: 1.8.3
[0m18:30:29.438064 [info ] [MainThread]: python version: 3.12.4
[0m18:30:29.438064 [info ] [MainThread]: python path: c:\venv\dbt\Scripts\python.exe
[0m18:30:29.438064 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m18:30:30.699309 [info ] [MainThread]: Using profiles dir at C:\Users\Felip\.dbt
[0m18:30:30.709799 [info ] [MainThread]: Using profiles.yml file at C:\Users\Felip\.dbt\profiles.yml
[0m18:30:30.709799 [info ] [MainThread]: Using dbt_project.yml file at c:\felipeyoshi\modern-data-stack\dbt\dbt_project.yml
[0m18:30:30.709799 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m18:30:30.709799 [debug] [MainThread]: Command `dbt debug` failed at 18:30:30.709799 after 1.42 seconds
[0m18:30:30.709799 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000169E9DEEEA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000169EA8846B0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000169EB543170>]}
[0m18:30:30.709799 [debug] [MainThread]: Flushing usage events
[0m18:33:07.595754 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017ED3600320>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017ED5E97740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017ED5E97800>]}


============================== 18:33:07.595754 | 6659cb50-fd1e-49a2-bef1-865e0fce2344 ==============================
[0m18:33:07.595754 [info ] [MainThread]: Running with dbt=1.8.3
[0m18:33:07.595754 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Felip\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m18:33:07.611382 [info ] [MainThread]: dbt version: 1.8.3
[0m18:33:07.611382 [info ] [MainThread]: python version: 3.12.4
[0m18:33:07.618968 [info ] [MainThread]: python path: c:\venv\dbt\Scripts\python.exe
[0m18:33:07.619427 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m18:33:07.824860 [info ] [MainThread]: Using profiles dir at C:\Users\Felip\.dbt
[0m18:33:07.824860 [info ] [MainThread]: Using profiles.yml file at C:\Users\Felip\.dbt\profiles.yml
[0m18:33:07.824860 [info ] [MainThread]: Using dbt_project.yml file at c:\felipeyoshi\modern-data-stack\dbt\dbt_project.yml
[0m18:33:07.824860 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m18:33:07.824860 [debug] [MainThread]: Command `dbt debug` failed at 18:33:07.824860 after 0.48 seconds
[0m18:33:07.824860 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017ED575F530>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017ECFA0B500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017ECFD53710>]}
[0m18:33:07.824860 [debug] [MainThread]: Flushing usage events
[0m18:33:49.153977 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020446153B00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020445E5C830>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020446153350>]}


============================== 18:33:49.153977 | 80dad8e1-c1c0-4959-8cbb-3a4c1f6798bd ==============================
[0m18:33:49.153977 [info ] [MainThread]: Running with dbt=1.8.3
[0m18:33:49.153977 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Felip\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt debug', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:33:49.171165 [info ] [MainThread]: dbt version: 1.8.3
[0m18:33:49.171165 [info ] [MainThread]: python version: 3.12.4
[0m18:33:49.171165 [info ] [MainThread]: python path: c:\venv\dbt\Scripts\python.exe
[0m18:33:49.171165 [info ] [MainThread]: os info: Windows-11-10.0.22631-SP0
[0m18:33:49.366792 [info ] [MainThread]: Using profiles dir at C:\Users\Felip\.dbt
[0m18:33:49.366792 [info ] [MainThread]: Using profiles.yml file at C:\Users\Felip\.dbt\profiles.yml
[0m18:33:49.366792 [info ] [MainThread]: Using dbt_project.yml file at c:\felipeyoshi\modern-data-stack\dbt\dbt_project.yml
[0m18:33:49.366792 [info ] [MainThread]: adapter type: snowflake
[0m18:33:49.382453 [info ] [MainThread]: adapter version: 1.8.3
[0m18:33:49.382453 [info ] [MainThread]: Configuration:
[0m18:33:49.382453 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m18:33:49.385712 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m18:33:49.385712 [info ] [MainThread]: Required dependencies:
[0m18:33:49.387372 [debug] [MainThread]: Executing "git --help"
[0m18:33:49.419194 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m18:33:49.419194 [debug] [MainThread]: STDERR: "b''"
[0m18:33:49.419194 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m18:33:49.419194 [info ] [MainThread]: Connection:
[0m18:33:49.419194 [info ] [MainThread]:   account: okb29290.us-east-1
[0m18:33:49.419194 [info ] [MainThread]:   user: fyoshimoto
[0m18:33:49.419194 [info ] [MainThread]:   database: analytics
[0m18:33:49.419194 [info ] [MainThread]:   warehouse: compute_wh
[0m18:33:49.419194 [info ] [MainThread]:   role: accountadmin
[0m18:33:49.435094 [info ] [MainThread]:   schema: adventureworks
[0m18:33:49.435094 [info ] [MainThread]:   authenticator: None
[0m18:33:49.435094 [info ] [MainThread]:   oauth_client_id: None
[0m18:33:49.435094 [info ] [MainThread]:   query_tag: None
[0m18:33:49.435094 [info ] [MainThread]:   client_session_keep_alive: False
[0m18:33:49.435094 [info ] [MainThread]:   host: None
[0m18:33:49.435094 [info ] [MainThread]:   port: None
[0m18:33:49.435094 [info ] [MainThread]:   proxy_host: None
[0m18:33:49.435094 [info ] [MainThread]:   proxy_port: None
[0m18:33:49.435094 [info ] [MainThread]:   protocol: None
[0m18:33:49.435094 [info ] [MainThread]:   connect_retries: 1
[0m18:33:49.435094 [info ] [MainThread]:   connect_timeout: None
[0m18:33:49.435094 [info ] [MainThread]:   retry_on_database_errors: False
[0m18:33:49.435094 [info ] [MainThread]:   retry_all: False
[0m18:33:49.435094 [info ] [MainThread]:   insecure_mode: False
[0m18:33:49.435094 [info ] [MainThread]:   reuse_connections: None
[0m18:33:49.435094 [info ] [MainThread]: Registered adapter: snowflake=1.8.3
[0m18:33:49.435094 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m18:33:49.435094 [debug] [MainThread]: Using snowflake connection "debug"
[0m18:33:49.435094 [debug] [MainThread]: On debug: select 1 as id
[0m18:33:49.435094 [debug] [MainThread]: Opening a new connection, currently in state init
[0m18:33:51.035854 [debug] [MainThread]: SQL status: SUCCESS 1 in 1.593 seconds
[0m18:33:51.035854 [debug] [MainThread]: On debug: Close
[0m18:33:51.483254 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m18:33:51.483254 [info ] [MainThread]: [31m1 check failed:[0m
[0m18:33:51.483254 [info ] [MainThread]: Project loading failed for the following reason:
 project path <c:\felipeyoshi\modern-data-stack\dbt\dbt_project.yml> not found

[0m18:33:51.483254 [debug] [MainThread]: Command `dbt debug` failed at 18:33:51.483254 after 2.44 seconds
[0m18:33:51.483254 [debug] [MainThread]: Connection 'debug' was properly closed.
[0m18:33:51.483254 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002044818E3C0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002044841C980>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020445DF3440>]}
[0m18:33:51.483254 [debug] [MainThread]: Flushing usage events
